# Generated by Django 6.0.4 on 2026-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_relance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
